---

- name: Deploy sample app to 'remote host'
  hosts: default

  vars:
    install_directory: app
    app_name: sendfile_test
    gem_dependecies:
      - libsqlite3-dev
    runtime_dependecies:
      - nodejs

  tasks:
    - name: Copy app
      # synchronize module doesn't work well with Vagrant;
      # ansible.cfg has our back
      # As the timestamp on db/ gets updated, we
      # ignore timestamps when sync'ing the app
      synchronize:
        dest: '{{ install_directory }}'
        src: '{{ app_name }}'
        use_ssh_args: true
        archive: false
        perms: true
        times: false
        recursive: true
        checksum: true
      notify:
        - Install gem build and runtime dependecies
        - Install gems
        - Load the database

  handlers:

    - name: Install gem build and runtime dependecies
      apt:
        name: '{{ item }}'
        state: present
      become: true
      with_items:
        - '{{ gem_dependecies }}'
        - '{{ runtime_dependecies }}'

    - name: Install gems
      bundler:
        chdir: '{{ install_directory }}/{{ app_name }}'
        deployment_mode: true
        state: present

    - name: Load the database
      command: bin/rake db:schema:load
      args:
        chdir: '{{ install_directory }}/{{ app_name }}'
      environment:
        RAILS_ENV: development
      register: out
      changed_when: out.stdout != ''
