---

- name: Install Ruby
  hosts: default

  vars_files:
    - vars.yml

  roles:
    - { name: zzet.rbenv }

  pre_tasks:
    - name: Remove conflicting packages
      apt:
        name: '{{ item }}'
        state: absent
      become: true
      with_items:
        - '{{ rbenv_apt_package_conflicts }}'

  tasks:
    - name: Read the requisite rbenv source block
      command: cat /etc/profile.d/rbenv.sh
      register: rbenv_bash
      changed_when: false
      check_mode: false

    - name: Prepend rbenv block to .bashrc
      blockinfile:
        path: .bashrc
        block: '{{ rbenv_bash.stdout }}'
        insertbefore: BOF
        state: present
        marker: '# {mark} ANSIBLE MANAGED BLOCK // rbenv'
