---

- name: Start app
  hosts: default

  vars_files:
    - vars.yml

  tasks:
    - name: Start service (daemon)
      command: bin/rails server --daemon --binding=0.0.0.0
      args:
        chdir: '{{ install_directory }}/{{ app_name }}'
      when: daemon | default (false)

    - name: Start service (backgrounded)
      shell: bin/rails server --binding=0.0.0.0 > /dev/null 2>&1 &
      args:
        chdir: '{{ install_directory }}/{{ app_name }}'
      async: 10
      poll: 0
      when: daemon | default (true)
